### ISSUE TITLE
sort without using useEffect?

### ISSUE THREAD

**Issue by encryptblockr** [KaterinaLupacheva/react-sorting-with-dropdown#3]
I see your solution here https://github.com/KaterinaLupacheva/react-sorting-with-dropdown/blob/master/src/App.js is to use `useEffect` but why do we need to use `useEffect`? since we already got our data already

it is similar to search, as long we got the data we just search from the data, why is sort not same? we have the data already, so sort that data

**Comment by KaterinaLupacheva** [comment]
We need to use the useEffect hook in order to sort the data dynamically, e.g. to run sortArray() function only when we change the sort type - the field name by which we would like to sort. This happens because the sortType variable is present in the dependencies array of the useEffect hook.

If you try to implement the same without the useEffect hook. like this:

```
function App() {
  const [data, setData] = useState([]);
  const [sortType, setSortType] = useState('albums');

  const sortArray = type => {
    const types = {
      albums: 'albums',
      members: 'members',
      formed: 'formed_in',
    };
    const sortProperty = types[type];
    const sorted = [...bands].sort((a, b) => b[sortProperty] - a[sortProperty]);
    setData(sorted);
  };

  sortArray(sortType);

  return (
    <div className="App">
      <select onChange={e => setSortType(e.target.value)}>
        <option value="albums">Albums</option>
        <option value="members">Members</option>
        <option value="formed">Formed in</option>
      </select>

      {data.map(band => (
        <div key={band.id} style={{ margin: '30px' }}>
          <div>{`Band: ${band.name}`}</div>
          <div>{`Albums: ${band.albums}`}</div>
          <div>{`Members: ${band.members}`}</div>
          <div>{`Year of founding: ${band.formed_in}`}</div>
        </div>
      ))}
    </div>
  );
}
```

you'll get the infinite loop, meaning your app will re-render constantly due to setData(...) function that updates the data to render (useState hook) all the time.

It's totally possible to sort the data without the useEffect hook. But only once:) Without changing the sort type dynamically.

**Comment by encryptblockr** [comment]
i see..sucks that it cant work well without useEffect because logically it should be able to...search works without useEffect...as long as data is available..it just searches that data..sort "should" be able to work same way too...sort the current data as is...and something should be updating the data

anyways thanks for your solution..appreciate it
